export enum AppRole {
  CLIENT_CREATE = 'ROLE_CLIENT_CREATE',
  CLIENT_UPDATE = 'ROLE_CLIENT_UPDATE',
  CLIENT_LIST = 'ROLE_CLIENT_LIST',
  CLIENT_DETAILS = 'ROLE_CLIENT_DETAILS',
  CLIENT_DELETE = 'ROLE_CLIENT_DELETE',

  CONTACT_CREATE = 'ROLE_CONTACT_CREATE',
  CONTACT_UPDATE = 'ROLE_CONTACT_UPDATE',
  CONTACT_LIST = 'ROLE_CONTACT_LIST',
  CONTACT_DETAILS = 'ROLE_CONTACT_DETAILS',
  CONTACT_DELETE = 'ROLE_CONTACT_DELETE',

  USER_CREATE = 'ROLE_USER_CREATE',
  USER_UPDATE = 'ROLE_USER_UPDATE',
  USER_LIST = 'ROLE_USER_LIST',
  USER_DETAILS = 'ROLE_USER_DETAILS',
  USER_DELETE = 'ROLE_USER_DELETE',

  MODULE_CREATE = 'ROLE_MODULE_CREATE',
  MODULE_UPDATE = 'ROLE_MODULE_UPDATE',
  MODULE_LIST = 'ROLE_MODULE_LIST',
  MODULE_DETAILS = 'ROLE_MODULE_DETAILS',
  MODULE_DELETE = 'ROLE_MODULE_DELETE',

  GROUP_CREATE = 'ROLE_GROUP_CREATE',
  GROUP_UPDATE = 'ROLE_GROUP_UPDATE',
  GROUP_LIST = 'ROLE_GROUP_LIST',
  GROUP_DETAILS = 'ROLE_GROUP_DETAILS',
  GROUP_DELETE = 'ROLE_GROUP_DELETE',

  ROLE_CREATE = 'ROLE_ROLE_CREATE',
  ROLE_UPDATE = 'ROLE_ROLE_UPDATE',
  ROLE_LIST = 'ROLE_ROLE_LIST',
  ROLE_DETAILS = 'ROLE_ROLE_DETAILS',
  ROLE_DELETE = 'ROLE_ROLE_DELETE',
}
