export enum AppRole {
  USER_CREATE = 'ROLE_USER_CREATE',
  USER_UPDATE = 'ROLE_USER_UPDATE',
  USER_LIST = 'ROLE_USER_LIST',
  USER_DETAILS = 'ROLE_USER_DETAILS',
  USER_DELETE = 'ROLE_USER_DELETE',

  GROUP_CREATE = 'ROLE_GROUP_CREATE',
  GROUP_UPDATE = 'ROLE_GROUP_UPDATE',
  GROUP_LIST = 'ROLE_GROUP_LIST',
  GROUP_DETAILS = 'ROLE_GROUP_DETAILS',
  GROUP_DELETE = 'ROLE_GROUP_DELETE',

  PROJECT_CREATE = 'ROLE_PROJECT_CREATE',
  PROJECT_UPDATE = 'ROLE_PROJECT_UPDATE',
  PROJECT_LIST = 'ROLE_PROJECT_LIST',
  PROJECT_DETAILS = 'ROLE_PROJECT_DETAILS',
  PROJECT_DELETE = 'ROLE_PROJECT_DELETE',

  ENVIRONMENT_CREATE = 'ROLE_ENVIRONMENT_CREATE',
  ENVIRONMENT_UPDATE = 'ROLE_ENVIRONMENT_UPDATE',
  ENVIRONMENT_LIST = 'ROLE_ENVIRONMENT_LIST',
  ENVIRONMENT_DETAILS = 'ROLE_ENVIRONMENT_DETAILS',
  ENVIRONMENT_DELETE = 'ROLE_ENVIRONMENT_DELETE',

  FEATURE_FLAG_CREATE = 'ROLE_FEATURE_FLAG_CREATE',
  FEATURE_FLAG_UPDATE = 'ROLE_FEATURE_FLAG_UPDATE',
  FEATURE_FLAG_LIST = 'ROLE_FEATURE_FLAG_LIST',
  FEATURE_FLAG_DETAILS = 'ROLE_FEATURE_FLAG_DETAILS',
  FEATURE_FLAG_DELETE = 'ROLE_FEATURE_FLAG_DELETE',

  AUDIT_LIST = 'ROLE_AUDIT_LIST',
  AUDIT_DETAILS = 'ROLE_AUDIT_DETAILS',

  API_TOKEN_CREATE = 'ROLE_API_TOKEN_CREATE',
  API_TOKEN_UPDATE = 'ROLE_API_TOKEN_UPDATE',
  API_TOKEN_LIST = 'ROLE_API_TOKEN_LIST',
  API_TOKEN_DETAILS = 'ROLE_API_TOKEN_DETAILS',
  API_TOKEN_DELETE = 'ROLE_API_TOKEN_DELETE',
}

export enum AppModuleName {
  USERS = 'users',
  GROUPS = 'groups',
  PROJECTS = 'projects',
  ENVIRONMENTS = 'environments',
  FEATURE_FLAGS = 'featureFlags',
  AUDIT = 'audit',
  API_TOKENS = 'apiTokens',
}

export const ModulesRolesMap: Record<AppModuleName, AppRole[]> = {
  [AppModuleName.USERS]: [
    AppRole.USER_CREATE,
    AppRole.USER_UPDATE,
    AppRole.USER_LIST,
    AppRole.USER_DETAILS,
    AppRole.USER_DELETE,
  ],
  [AppModuleName.GROUPS]: [
    AppRole.GROUP_CREATE,
    AppRole.GROUP_UPDATE,
    AppRole.GROUP_LIST,
    AppRole.GROUP_DETAILS,
    AppRole.GROUP_DELETE,
  ],
  [AppModuleName.PROJECTS]: [
    AppRole.PROJECT_CREATE,
    AppRole.PROJECT_UPDATE,
    AppRole.PROJECT_LIST,
    AppRole.PROJECT_DETAILS,
    AppRole.PROJECT_DELETE,
  ],
  [AppModuleName.ENVIRONMENTS]: [
    AppRole.ENVIRONMENT_CREATE,
    AppRole.ENVIRONMENT_UPDATE,
    AppRole.ENVIRONMENT_LIST,
    AppRole.ENVIRONMENT_DETAILS,
    AppRole.ENVIRONMENT_DELETE,
  ],
  [AppModuleName.FEATURE_FLAGS]: [
    AppRole.FEATURE_FLAG_CREATE,
    AppRole.FEATURE_FLAG_UPDATE,
    AppRole.FEATURE_FLAG_LIST,
    AppRole.FEATURE_FLAG_DETAILS,
    AppRole.FEATURE_FLAG_DELETE,
  ],
  [AppModuleName.AUDIT]: [
    AppRole.AUDIT_LIST,
    AppRole.AUDIT_DETAILS,
  ],
  [AppModuleName.API_TOKENS]: [
    AppRole.API_TOKEN_CREATE,
    AppRole.API_TOKEN_UPDATE,
    AppRole.API_TOKEN_LIST,
    AppRole.API_TOKEN_DETAILS,
    AppRole.API_TOKEN_DELETE,
  ],
};

export function allRoles(): AppRole[] {
  return Object.values(ModulesRolesMap).flat();
}
